### PR TITLE
refactor: add 'force' svar and factor out cm cond

### PR DESCRIPTION
**Pull request by ThisAMJ**
This more modular setup allows for users to control precisely when they use mtriggers. Mainly for those without srconfigs running Any% or anybody doing TASing.

### CODE REVIEW

**Comment by mlugg** [comment]
I like the *idea* of this PR, but the implementation is... weird? It makes some changes for no good reason. In particular, there's no advantage to special-casing the support for srconfigs; it neither helps srconfigs users nor other people, and I'd prefer any stuff in srconfigs support to be handled actually within srconfigs. Could you change the PR so it uses the following logic? This is flexible but retains back-compat and doesn't unnecessarily integrate with srconfigs.
```
sar_on_load svar_set __mtriggers_enable 0
sar_on_load cond "(cm | ?force_mtriggers=1) & !?no_mtriggers=1" svar_set __mtriggers_enable 1
```

**Comment by ThisAMJ** [comment]
Sure, but I feel like `no_mtriggers` isn't a great solution going forward, just because it's logically convoluted -- 'if there's not no mtriggers enable them'

**Comment by ThisAMJ** [comment]
Also the functionality of `force_mtriggers` is meant to be independent of anything the configs are doing (your ver. can't force them *off*)

**Comment by mlugg** [comment]
I mean... It can, just set 'no_mtriggers'. All mine does is splits the functionality - I agree it's a slightly worse method than one svar but back compat is at least sorta important here - no_mtriggers doesn't seem confusing to me at all, it just disables mtriggers. Only issue is that it's just slightly redundant compared to a single svar but no biggie

**Pull request merged**
