### PR TITLE
sar_on_loads into one

### PR DESCRIPTION
**Pull request by ThisAMJ**
I could also merge all the mtriggers into the main file (one large file > many small files for a number of reasons, including performance which mlugg has commented on) but he seems opposed to that for the sake of neatness.

Also fixes a swapped trigger pair.

### CODE REVIEW

**Comment by mlugg** [comment]
I don't particularly see the point of putting all the sar_on_loads in one exec; it won't help performance at all, and IMO is much less neat. What was the reasoning for this?
The other two changes are reasonable though, I'll definitely merge those in

**Comment by ThisAMJ** [comment]
The sar_on_loads being in one exec can help mtrigger editing/creation live, by just moving the one sar_on_load from mtriggers.cfg into autoexec and running `sar_speedrun_reset_categories yes; exec mtriggers` to update mtriggers. In all sar_on_load use-cases, a more editable approach such as this can be helpful.

Merging all the mtriggers into one file can significantly improve load times for Linux users, and the only argument against it is 'neatness'? In truth, I don't happen to remember the file name of every map, so sp_a3_whatever has no meaning to me and makes it less neat in my opinion.

**Comment by mlugg** [comment]
> The sar_on_loads being in one exec doesn't _hinder_ performance at all either, and can help mtrigger editing/creation live, by just moving the one sar_on_load from mtriggers.cfg into autoexec and running `sar_speedrun_reset_categories yes; exec mtriggers` to update mtriggers. In all sar_on_load use-cases, a more editable approach such as this can be helpful.

Okay, that's an interesting point, however still not actually necessary for two reasons:
a) registering the sar_on_load's twice really isn't a big deal
b) you can just as easily move the sar_on_load from the specific file into your autoexec; there's nothing special about mtriggers.cfg

> Merging all the mtriggers into one file can significantly improve load times for Linux users, and the only argument against it is 'neatness'? In truth, I don't happen to remember the file name of every map, so sp_a3_whatever has no meaning to me and makes it less neat in my opinion.

The speed improvement is just a one-time thing from actually creating the triggers, so imo is not hugely important, especially since it's only a couple seconds. Having all the categories in one file is *very* inelegant; that file would literally be around 1500 lines long, and is much harder to understand and work with than the hierarchical structure we currently have. The argument on file names is a valid one though; you could make the argument that the files should be renamed to reflect the human-readable map names rather than the internal ones. Feel free to make a PR for that change in fact; I think it's probably a good idea!

**Comment by mlugg** [comment]
Merged in d9d5d0, 060c00b, and fe20c83

**Pull request closed without merging**
